<div class="sequences">
 <table>
   <tr>
     <td class="sequence">
       <h3>Cleansheets</h3>
       $aggregatetable(aggregate=aggregates.("Cleansheets"))$
     </td>
     <td class="sequence">
       <h3>Blanks</h3>
       $aggregatetable(aggregate=aggregates.("Blanks"))$
     </td>
     <td class="sequence">
       <h3>No-Score Draws</h3>
       $aggregatetable(aggregate=aggregates.("BoreDraws"))$
     </td>
   </tr>
 </table>
</div>
<div class="clearfloat"></div>
