$header(title="Current Sequences")$
<div id="centre">
  $selector()$
  $tabs()$
  <div id="content">
    <h2>$metaData.division$ $metaData.season$ - Current Sequences</h2>
    <p>
      <strong>Current</strong> unbroken sequences for <strong>all matches (home and away)</strong>.
      Move your mouse over the numbers to see the sequence details.
    </p>
    $sequences()$
  </div>
  <div id="bottomtabs">
    <div class="tab selectedtab">
      <a href="#">Overall</a>
    </div>
    <div class="tab">
      <a href="homecurrentsequences.html">Home</a>
    </div>
    <div class="tab">
      <a href="awaycurrentsequences.html">Away</a>
    </div>
  </div>
</div>
$footer()$

