    </div><!-- Container -->
    <div id="footer">
      <div class="container">
        <p class="muted text-center">
          Powered by <a href="https://github.com/dwdyer/anorak">Anorak</a>.
        </p>
      </div>
    </div>
    <script type="text/javascript">
      var leagueName  = "$metaData.league$";
      var divisionName  = "$metaData.division$";
      var seasonName = "$metaData.season$";
    </script>
    <script type="text/javascript" src="../../../anorak.js"></script>
    <script type="text/javascript" src="../../../sorttable.js"></script>
  </body>
</html>
