<!DOCTYPE html>
<html lang="en">
  <head>
    <title>$metaData.division$ $metaData.season$ - $title$</title>
    <meta charset="utf-8">
    <link href="../../../css/bootstrap.min.css" rel="stylesheet">
    <link href="../../../css/anorak.css" rel="stylesheet" type="text/css">
    $if(bootstrapJS)$
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script type="text/javascript" src="../../../js/bootstrap.min.js"></script>
    $endif$
  </head>
  <body>
    <div class="container">
