<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
    <title>$metaData.division$ $metaData.season$ - $title$</title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    $if(!metaData.isArchive)$
    <meta http-equiv="Cache-Control" content="max-age=7200" />
    $endif$
    <link href="../../../anorak.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript">
      var leagueName  = "$metaData.league$";
      var divisionName  = "$metaData.division$";
      var seasonName = "$metaData.season$";
    </script>
    <script type="text/javascript" src="../../../anorak.js"></script>
    <script type="text/javascript" src="../../../sorttable.js"></script>
  </head>
  <body>
    <div id="container">
