$header(title="Longest Home Sequences")$
<div id="centre">
  $selector()$
  $tabs()$
  <div id="content">
    <h2>$metaData.division$ $metaData.season$ - Longest Home Sequences</h2>
    <p>
      The longest sequences achieved by each team in <strong>home matches only</strong>.
      Move your mouse over the numbers to see the sequence details.
    </p>
    $sequences()$
  </div>
  <div id="bottomtabs">
    <div class="tab">
      <a href="longestsequences.html">Overall</a>
    </div>
    <div class="tab selectedtab">
      <a href="#">Home</a>
    </div>
    <div class="tab">
      <a href="awaylongestsequences.html">Away</a>
    </div>
  </div>
</div>
$footer()$

