$header(title="Current Home Sequences")$
<div id="centre">
  $selector()$
  $tabs()$
  <div id="content">
    <h2>$metaData.division$ $metaData.season$ - Current Home Sequences</h2>
    <p>
      <strong>Current</strong> unbroken sequences for <strong>home matches only</strong>.
      Move your mouse over the numbers to see the sequence details.
    </p>
    $sequences()$
  </div>
  <div id="bottomtabs">
    <div class="tab">
      <a href="currentsequences.html">Overall</a>
    </div>
    <div class="tab selectedtab">
      <a href="#">Home</a>
    </div>
    <div class="tab">
      <a href="awaycurrentsequences.html">Away</a>
    </div>
  </div>
</div>
$footer()$

