$header(title="Longest Sequences")$
<div id="centre">
  $selector()$
  $tabs()$
  <div id="content">
    <h2>$metaData.division$ $metaData.season$ - Longest Sequences</h2>
    <p>
      The longest sequences achieved by each team in <strong>all matches (home and away)</strong>.
      Move your mouse over the numbers to see the sequence details.
    </p>
    $sequences()$
  </div>
  <div id="bottomtabs">
    <div class="tab selectedtab">
      <a href="#">Overall</a>
    </div>
    <div class="tab">
      <a href="homelongestsequences.html">Home</a>
    </div>
    <div class="tab">
      <a href="awaylongestsequences.html">Away</a>
    </div>
  </div>
</div>
$footer()$

