<tr><td colspan="3" class="matchday" id="$it.("0");format="%Y%m%d"$">$it.("0");format="%A %e %B %Y"$</td></tr>
$it.("1"):{<tr>
  <td class="hometeam"><a href="$metaData.teamLinks.(it.homeTeam)$">$it.homeTeam$</a></td>
  <td class="score">$it.homeScore$&nbsp;-&nbsp;$it.awayScore$</td>
  <td class="awayteam"><a href="$metaData.teamLinks.(it.awayTeam)$">$it.awayTeam$</a></td>
</tr>}$
<tr><td colspan="3">&nbsp;</td></tr>
