<div class="navbar navbar-inverse navbar-fixed-top">
  <div id="selector" class="navbar-inner">
    <div class="container">
      <a href="https://github.com/dwdyer/anorak" class="brand">Anorak</a>
      <form class="navbar-form pull-right">
        <select id="leagues">
          <option>Loading...</option>
        </select>
        <select id="divisions">
          <option>Loading...</option>
        </select>
        <select id="seasons">
          <option>Loading...</option>
        </select>
      </form>
    </div>
  </div>
</div>
