<div class="row">
  <div class="span3 sequence">
    <h4>Wins</h4>
    $sequencetable(sequence=sequences.("Wins");n="W")$
  </div>
  <div class="span3 sequence">
    <h4>Draws</h4>
    $sequencetable(sequence=sequences.("Draws");n="D")$
  </div>
  <div class="span3 sequence">
    <h4>Defeats</h4>
    $sequencetable(sequence=sequences.("Losses");n="L")$
  </div>
</div>
<div class="row">
  <div class="span3 sequence">
    <h4>Unbeaten</h4>
    $sequencetable(sequence=sequences.("Unbeaten");n="U")$
  </div>
  <div class="span3 sequence">
    <h4>Cleansheets</h4>
    $sequencetable(sequence=sequences.("Cleansheets");n="CS")$
  </div>
  <div class="span3 sequence">
    <h4>Matches Scored In</h4>
    $sequencetable(sequence=sequences.("Scored");n="S")$
  </div>
</div>
<div class="row">
  <div class="span3 sequence">
    <h4>Without A Win</h4>
    $sequencetable(sequence=sequences.("NoWin");n="NW")$
  </div>
  <div class="span3 sequence">
    <h4>Without A Cleansheet</h4>
    $sequencetable(sequence=sequences.("Conceded");n="C")$
  </div>
  <div class="span3 sequence">
    <h4>Without Scoring</h4>
    $sequencetable(sequence=sequences.("NoGoal");n="NG")$
  </div>
</div>
