<table class="mainsequences">
  <tr>
    <td class="sequence">
      <h3>Wins</h3>
      $sequencetable(sequence=sequences.("Wins"))$
    </td>
    <td class="sequence">
      <h3>Draws</h3>
      $sequencetable(sequence=sequences.("Draws"))$
    </td>
    <td class="sequence">
      <h3>Defeats</h3>
      $sequencetable(sequence=sequences.("Losses"))$
    </td>
  </tr>
</table>
<table>
  <tr>
    <td class="sequence">
      <h3>Unbeaten</h3>
      $sequencetable(sequence=sequences.("Unbeaten"))$
      <h3>Without A Win</h3>
      $sequencetable(sequence=sequences.("NoWin"))$
    </td>
    <td class="sequence">
      <h3>Cleansheets</h3>
      $sequencetable(sequence=sequences.("Cleansheets"))$
      <h3>Without A Cleansheet</h3>
      $sequencetable(sequence=sequences.("Conceded"))$
    </td>
    <td class="sequence">
      <h3>Matches Scored In</h3>
      $sequencetable(sequence=sequences.("Scored"))$
      <h3>Without Scoring</h3>
      $sequencetable(sequence=sequences.("NoGoal"))$
    </td>
  </tr>
</table>

