<table>
  $sequence:{<tr>
    <td><a href="$it.("1")$">$it.("0")$</a></td>
    <td class="number" onmouseover="this.className='number hover';return true;" onmouseout="this.className='number';return true;">
      <span class="hotspot">$length(it.("2"))$</span
      ><div class="shadowwrapper">
        <div class="details">
          <div class="shadow"></div>
          <strong>$it.("0")$</strong>
          $details(results=it.("1"))$
        </div>
      </div>
    </td>
  </tr>}$
</table>

